export const routes = {
  urunler: "/urunler",
  urundetay: "/urunler/",
  talepler: "/talepler/",
  talepdetay: "/talepler/",
  yenitalep: "/talepler/yeni",
  yenitalepUrun: "/talepler/urun/yeni",
  yeniurun: "/urunler/yeni",
  urunguncelle: "/urunler/guncelle",
  newcompany: "/firmalar/yeni",
  company: "/firmalar",
  companydetail: "/firmalar/",
  yeniAlternatif: "/talep/alternatif/yeni",
  alternatif: "/talep/alternatif",
  alternatifDetay: "/talep/alternatif/",
};
