export const routes = {
  urunler: "/urunler",
  urundetay: "/urun-detay/detay/",
  talepler: "/talepler/",
  talepdetay: "/talepler/",
  yenitalep: "/talepler/yeni",
  yenitalepUrun: "/talepler/urun/yeni",
  yeniurun: "/urunler/yeni",
  urunguncelle: "/urunler/guncelle",
  newcompany: "/firmalar/yeni",
  company: "/firmalar",
  companydetail: "/firmalar/",
  yeniAlternatif: "/talepler/alternatifler/yeni",
  alternatif: "/talepler/alternatifler",
  alternatifGuncelle: "/talepler/alternatifler/guncelle",
  gorevler: "/urun-detay/gorevler/:id/fiyatarastirma",
  maliyetler: "/urun-detay/maliyetler/",
  teklif: "/urun-detay/teklif/",
  yenifiyat: "/urun-detay/gorevler/fiyatarastirma/yeni",
  fiyatdetay: "/urun-detay/gorevler/fiyatarastirma/",
  yeniLojistik: "/urun-detay/gorevler/lojistik/yeni",
  lojistikDetay: "/urun-detay/gorevler/lojistik/",
  lojistik: "/urun-detay/gorevler/lojistik/",
  urunSertifika:"/urun-detay/sertifika/"
};
