export const routes = {
  urunler: "/urunler",
  urundetay: "/urunler/",
  talepler: "/talepler/",
  talepdetay: "/talepler/",
  yenitalep: "/talepler/yeni",
  yenitalepUrun: "/talepler/urun/yeni",
  yeniurun: "/urunler/yeni",
  urunguncelle: "/urunler/guncelle",
  newcompany: "/firmalar/yeni",
  company: "/firmalar",
  companydetail: "/firmalar/",
  yeniAlternatif: "/talepler/alternatifler/yeni",
  alternatif: "/talepler/alternatifler",
  alternatifGuncelle: "/talepler/alternatifler/guncelle",
  gorevler: "/gorevler/:id",
  maliyetler: "/maliyetler",
  teklif: "/teklif",
  yenifiyat: "/gorevler/fiyatarastirma/yeni",
  fiyatdetay: "/gorevler/fiyatarastirma/",
  yeniLojistik: "/gorevler/lojistik/yeni",
  lojistikDetay: "/gorevler/lojistik/",
  lojistik: "/gorevler/lojistik/",
};
