export const TALEP_LIST_SUCCESS = "TALEP_LIST_SUCCESS";
export const TALEP_GET_SUCCESS = "TALEP_GET_SUCCESS";

export const TALEPURUN_LIST_SUCCESS = "TALEPURUN_LIST_SUCCESS";
export const TALEPURUN_GET_SUCCESS = "TALEPURUN_GET_SUCCESS";
export const TALEPURUN_INSERT_SUCCESS = "TALEPURUN_INSERT_SUCCESS";
export const TALEPURUN_UPDATE_SUCCESS = "TALEPURUN_UPDATE_SUCCESS";
export const TALEPURUN_REMOVE_SUCCESS = "TALEPURUN_REMOVE_SUCCESS";


export const TALEP_REQUEST = "TALEP_REQUEST";
export const TALEP_ERROR = "TALEP_ERROR";